# Generated by Django 3.2.19 on 2023-07-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='greet', max_length=20, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
